### ISSUE TITLE
Receive an error when running the server

### ISSUE THREAD

**Issue by Oliversw** [fac-15/Spellchecker#20]
When we first tried to run your server we received this error:
```$ node src/server.js
/Users/Oliver/Dropbox/Founders-and-Coders/Week 4/Spellchecker/src/handlers.js:70
});
 ^

SyntaxError: Unexpected token )
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

We were able to fix it by placing an extra closing curly brace at the bottom of your handlers file, after which we were able to run the server. However, as soon as we tried to visit http://localhost:3000/, we received another error:

```$ node src/server.js
hi
Server is listening on port 3000.  Ready to accept requests! ```




```$ node src/server.js
hi
Server is listening on port 3000.  Ready to accept requests!
I am inside the router
URL: /
/Users/Oliver/Dropbox/Founders-and-Coders/Week 4/Spellchecker/src/router.js:19
    handlers.handleHomeRoute(request, response);
             ^

TypeError: handlers.handleHomeRoute is not a function
    at Server.router (/Users/Oliver/Dropbox/Founders-and-Coders/Week 4/Spellchecker/src/router.js:19:14)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:652:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
Oliver (master *) Spellchecker
$ 
```

No idea what's happening, sorry!

**Comment by Oliversw** [comment]
The error for the CSS and favicon is net ```::ERR_CONNECTION_REFUSED``` by the way!

**Comment by boi87** [comment]
![image](https://user-images.githubusercontent.com/25410752/48939354-db6f8e00-ef0b-11e8-936a-b8547d908f12.png)
